# Site settings
title: Developeratations
email: dldorsey@gmail.com
description: "aitch tee tee pee cee o el o en ess el a ess aitch ess el a ess aitch double-u double-u double-u"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/essemteepee
  - title: facebook
    url: http://facebook.com/lisasbrother
  - title: bitbucket 
    url: http://bitbucket.org/dldorsey
  - title: github
    url: http://github.com/dldorsey

# Postal address (add as many lines as necessary)
address:
  - line: 8819 Oak Trail
  - line: Jessup, MD 20794

# Build settings
markdown: kramdown
permalink: pretty
